# Generated by Django 3.0 on 2022-06-06 21:14

from django.apps import apps as global_apps
from django.db import migrations


def forwards(apps, schema_editor):
    try:
        profile_old = apps.get_model('oc_lettings_site', 'Profile')
    except LookupError:
        # The old app isn't installed.
        return

    profile_new = apps.get_model('profiles', 'Profile')

    for old_object in profile_old.objects.all():
        profile_dict = old_object.__dict__
        del profile_dict['_state']
        del profile_dict['id']

        # profile_new.objects.bulk_creat
        profile_new.objects.create(**profile_dict)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

    if global_apps.is_installed('oc_lettings_site'):
        dependencies.append(('oc_lettings_site', '0001_initial'))
