version: 2.1


workflows:
  main:
    jobs:
      - build-and-test
      - build-push-docker:
          requires:
            - build-and-test


jobs:

  build-and-test:

    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Installing dependencies
          command: pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Runing tests
          command: pytest

      - run:
          name: Lingting with flake8
          command: flake8

  build-push-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_HUB_USERNAME/$DOCKER_REPO_NAME:$CIRCLE_SHA1 .
      - run:
          name: Loging to Docker
          command: |
            echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      # build the application image
      - run:
          name: Building the Docker Image
          command: docker tag $DOCKER_HUB_USERNAME/$DOCKER_REPO_NAME:$CIRCLE_SHA1 $DOCKER_HUB_USERNAME/$DOCKER_REPO_NAME:latest

      # deploy the image
      # - run: docker push $DOCKER_HUB_USERNAME/$DOCKER_REPO_NAME:$CIRCLE_SHA1